# Generated by Django 5.2 on 2025-05-07 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_true', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=100)),
                ('details', models.TextField(max_length=500)),
                ('link', models.TextField(max_length=500)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
    ]
