# Generated by Django 5.2 on 2025-05-10 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learnApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price_course',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
