# Generated by Django 5.2 on 2025-05-07 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learnApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='slug',
            field=models.SlugField(default='default-slug', unique=True),
        ),
    ]
